name: Build mihomo AD files
on:
  workflow_dispatch:
  schedule:
    - cron: "00 00 * * *"
  push:
    branches:
      - master
    paths-ignore:
      - "**/README.md"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get AD domains
        run: |
          wget -O reject-list1.txt https://raw.githubusercontent.com/CHIZI-0618/v2ray-rules-dat/release/reject-list.txt
          wget -O reject-list2.txt https://raw.githubusercontent.com/Cats-Team/AdRules/main/adrules.list
          wget -O reject-list3.txt https://raw.githubusercontent.com/TG-Twilight/AWAvenue-Ads-Rule/main/Filters/AWAvenue-Ads-Rule-Clash.yaml
      - name: Add DOMAIN-SET
        run: |
          sed -i "s/^/- '+./" reject-list1.txt
          sed -i "s/$/'/" reject-list1.txt
          sed -i "s/DOMAIN-SUFFIX,/- '+./g" reject-list2.txt
          sed -i "/^#.*/d" reject-list2.txt
          sed -i "s/$/'/" reject-list2.txt
          sed -i "/^#.*/d" reject-list3.txt
          sed -i "/^payload.*/d" reject-list3.txt
          sed -i "s/$/'/" reject-list3.txt
          sed -e "$r reject-list3.txt" reject-list2.txt reject-list1.txt >> reject-list.txt
          sort reject-list.txt | uniq > reject.txt
          rm -f reject-list.txt reject-list1.txt reject-list2.txt reject-list3.txt
          sed -i '1i\payload:' reject.txt
          update_time="$(TZ=UTC-8 date +'%Y-%m-%d %H:%M:%S')(GMT+8)"
          sed -i '1i\#自动更新时间: '"$update_time"'' reject.txt
      - name: Git push assets to "release" branch
        run: |
          git init
          git config --local user.email "github-action@users.noreply.github.com"
          git config --local user.name "GitHub Action"
          git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git branch -M release
          git add .
          git commit -m "Update release"
          git push -f -u origin release
