name: Build mihomo AD files
on:
  workflow_dispatch:
  schedule:
    - cron: "00 00 * * *"
  push:
    branches:
      - master
    paths-ignore:
      - "**/README.md"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get AD domains
        run: |
          wget -O reject.txt https://ruleset.skk.moe/Clash/domainset/reject.txt
      - name: Add DOMAIN-SET
        run: |
          sed -i "/^#.*/d" reject.txt
          sed -i "s/^/- '/" reject.txt
          sed -i "s/$/'/" reject.txt
          sed -i 1i\payload: reject.txt
          update_time="$(TZ=UTC-8 date +'%Y-%m-%d %H:%M:%S')(GMT+8)"
          sed -i '1i\#自动更新时间: '"$update_time"'' reject.txt
      - name: Git push assets to "release" branch
        run: |
          git init
          git config --local user.email "github-action@users.noreply.github.com"
          git config --local user.name "GitHub Action"
          git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git branch -M release
          git add .
          git commit -m "Update release"
          git push -f -u origin release
